### ISSUE TITLE
Removing Virtus dependency

### ISSUE THREAD

**Issue by PericlesTheo** [gocardless/companies-house-rest#64]
Hey folks,

Since [Virtus](https://github.com/solnic/virtus) has been discontinued, how do you feel about replacing it with let's say [dry-types](https://dry-rb.org/gems/dry-types/)? Same author, same functionality I think.

This is not in any way a needed change, the gem is fine with Virtus. More of a suggestion 😃 Happy to create a PR.

**Comment by nickcampbell18** [comment]
I like the idea, a PR would be very welcome thanks!
